/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon;

import javax.swing.ImageIcon;

/**
 *
 * @author PauloSenires
 */
public class PokemonSelection extends javax.swing.JFrame {

    /**
     * Creates new form PokemonSelection
     */
    public PokemonSelection() {
        initComponents();
    }

    int[] pokemons;
    int[] livesPercentage = {100, 100, 100, 100, 100, 100};
    int counter = 1;
    int counter2 = 1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Bulbasaur = new javax.swing.JButton();
        Squirtle = new javax.swing.JButton();
        Charmander = new javax.swing.JButton();
        Pikachu = new javax.swing.JButton();
        Zapdos = new javax.swing.JButton();
        Articuno = new javax.swing.JButton();
        Pichu = new javax.swing.JButton();
        Moltres = new javax.swing.JButton();
        Cyndaquil = new javax.swing.JButton();
        Chikorita = new javax.swing.JButton();
        Totodile = new javax.swing.JButton();
        Clefable = new javax.swing.JButton();
        Elekid = new javax.swing.JButton();
        Igglybuff = new javax.swing.JButton();
        Teddyursa = new javax.swing.JButton();
        Togepi = new javax.swing.JButton();
        Smoochum = new javax.swing.JButton();
        Magby = new javax.swing.JButton();
        Lugia = new javax.swing.JButton();
        Latias = new javax.swing.JButton();
        Celebi = new javax.swing.JButton();
        Torchic = new javax.swing.JButton();
        Treeko = new javax.swing.JButton();
        Mudkip = new javax.swing.JButton();
        Latios = new javax.swing.JButton();
        Tepig = new javax.swing.JButton();
        Turtwig = new javax.swing.JButton();
        Piplup = new javax.swing.JButton();
        Raiku = new javax.swing.JButton();
        Chimchar = new javax.swing.JButton();
        Snivy = new javax.swing.JButton();
        Oshawott = new javax.swing.JButton();
        Suicune = new javax.swing.JButton();
        Entei = new javax.swing.JButton();
        Larvitar = new javax.swing.JButton();
        Hooh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Zapdos1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        party4 = new javax.swing.JButton();
        party5 = new javax.swing.JButton();
        party3 = new javax.swing.JButton();
        party2 = new javax.swing.JButton();
        party1 = new javax.swing.JButton();
        party6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bulbasaur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/bulbasaur.png"))); // NOI18N
        Bulbasaur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulbasaurActionPerformed(evt);
            }
        });
        getContentPane().add(Bulbasaur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, 40, 40));

        Squirtle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/squirtle.png"))); // NOI18N
        Squirtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquirtleActionPerformed(evt);
            }
        });
        getContentPane().add(Squirtle, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 66, 40, 40));

        Charmander.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/charmander.png"))); // NOI18N
        Charmander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharmanderActionPerformed(evt);
            }
        });
        getContentPane().add(Charmander, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 66, 40, 40));

        Pikachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/pikachu.png"))); // NOI18N
        Pikachu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PikachuActionPerformed(evt);
            }
        });
        getContentPane().add(Pikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 66, 40, 40));

        Zapdos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/zapdos.png"))); // NOI18N
        Zapdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZapdosActionPerformed(evt);
            }
        });
        getContentPane().add(Zapdos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 66, 40, 40));

        Articuno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/articuno.png"))); // NOI18N
        Articuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticunoActionPerformed(evt);
            }
        });
        getContentPane().add(Articuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 66, 40, 40));

        Pichu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/pichu.png"))); // NOI18N
        Pichu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PichuActionPerformed(evt);
            }
        });
        getContentPane().add(Pichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 112, 40, 40));

        Moltres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/moltres.png"))); // NOI18N
        Moltres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoltresActionPerformed(evt);
            }
        });
        getContentPane().add(Moltres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 112, 40, 40));

        Cyndaquil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/cyndaquil.png"))); // NOI18N
        Cyndaquil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CyndaquilActionPerformed(evt);
            }
        });
        getContentPane().add(Cyndaquil, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 112, 40, 40));

        Chikorita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/chikorita.png"))); // NOI18N
        Chikorita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChikoritaActionPerformed(evt);
            }
        });
        getContentPane().add(Chikorita, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 112, 40, 40));

        Totodile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/totodile.png"))); // NOI18N
        Totodile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotodileActionPerformed(evt);
            }
        });
        getContentPane().add(Totodile, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 112, 40, 40));

        Clefable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/cleffa.png"))); // NOI18N
        Clefable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClefableActionPerformed(evt);
            }
        });
        getContentPane().add(Clefable, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 112, 40, 40));

        Elekid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/elekid.png"))); // NOI18N
        Elekid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElekidActionPerformed(evt);
            }
        });
        getContentPane().add(Elekid, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 158, 40, 40));

        Igglybuff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/igglybuff.png"))); // NOI18N
        Igglybuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgglybuffActionPerformed(evt);
            }
        });
        getContentPane().add(Igglybuff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 158, 40, 40));

        Teddyursa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/teddiursa.png"))); // NOI18N
        Teddyursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeddyursaActionPerformed(evt);
            }
        });
        getContentPane().add(Teddyursa, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 158, 40, 40));

        Togepi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/togepi.png"))); // NOI18N
        Togepi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TogepiActionPerformed(evt);
            }
        });
        getContentPane().add(Togepi, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 158, 40, 40));

        Smoochum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/smoochum.png"))); // NOI18N
        Smoochum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmoochumActionPerformed(evt);
            }
        });
        getContentPane().add(Smoochum, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 158, 40, 40));

        Magby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/magby.png"))); // NOI18N
        Magby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagbyActionPerformed(evt);
            }
        });
        getContentPane().add(Magby, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 158, 40, 40));

        Lugia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/lugia.png"))); // NOI18N
        Lugia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugiaActionPerformed(evt);
            }
        });
        getContentPane().add(Lugia, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 204, 40, 40));

        Latias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/latias.png"))); // NOI18N
        Latias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatiasActionPerformed(evt);
            }
        });
        getContentPane().add(Latias, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 250, 40, 40));

        Celebi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/celebi.png"))); // NOI18N
        Celebi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelebiActionPerformed(evt);
            }
        });
        getContentPane().add(Celebi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 40, 40));

        Torchic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/torchic.png"))); // NOI18N
        Torchic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TorchicActionPerformed(evt);
            }
        });
        getContentPane().add(Torchic, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 250, 40, 40));

        Treeko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/treecko.png"))); // NOI18N
        Treeko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreekoActionPerformed(evt);
            }
        });
        getContentPane().add(Treeko, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 250, 40, 40));

        Mudkip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/mudkip.png"))); // NOI18N
        Mudkip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MudkipActionPerformed(evt);
            }
        });
        getContentPane().add(Mudkip, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 250, 40, 40));

        Latios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/latios.png"))); // NOI18N
        Latios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatiosActionPerformed(evt);
            }
        });
        getContentPane().add(Latios, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 40, 40));

        Tepig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/tepig.png"))); // NOI18N
        Tepig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TepigActionPerformed(evt);
            }
        });
        getContentPane().add(Tepig, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 296, 40, 40));

        Turtwig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/turtwig.png"))); // NOI18N
        Turtwig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurtwigActionPerformed(evt);
            }
        });
        getContentPane().add(Turtwig, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 296, 40, 40));

        Piplup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/piplup.png"))); // NOI18N
        Piplup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiplupActionPerformed(evt);
            }
        });
        getContentPane().add(Piplup, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 296, 40, 40));

        Raiku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/raikou.png"))); // NOI18N
        Raiku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaikuActionPerformed(evt);
            }
        });
        getContentPane().add(Raiku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 204, 40, 40));

        Chimchar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/chimchar.png"))); // NOI18N
        Chimchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChimcharActionPerformed(evt);
            }
        });
        getContentPane().add(Chimchar, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 296, 40, 40));

        Snivy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/snivy.png"))); // NOI18N
        Snivy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnivyActionPerformed(evt);
            }
        });
        getContentPane().add(Snivy, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 296, 40, 40));

        Oshawott.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/oshawott.png"))); // NOI18N
        Oshawott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OshawottActionPerformed(evt);
            }
        });
        getContentPane().add(Oshawott, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 296, 40, 40));

        Suicune.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/suicune.png"))); // NOI18N
        Suicune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuicuneActionPerformed(evt);
            }
        });
        getContentPane().add(Suicune, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 204, 40, 40));

        Entei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/entei.png"))); // NOI18N
        Entei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnteiActionPerformed(evt);
            }
        });
        getContentPane().add(Entei, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 204, 40, 40));

        Larvitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/larvitar.png"))); // NOI18N
        Larvitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LarvitarActionPerformed(evt);
            }
        });
        getContentPane().add(Larvitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 204, 40, 40));

        Hooh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/ho-oh.png"))); // NOI18N
        Hooh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoohActionPerformed(evt);
            }
        });
        getContentPane().add(Hooh, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 204, 40, 40));

        jLabel1.setFont(new java.awt.Font("Lao UI", 0, 14)); // NOI18N
        jLabel1.setText("Select your team!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, 139, 49));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 180));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 180));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, 180));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 180));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 180));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        Zapdos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/zapdos.png"))); // NOI18N
        Zapdos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zapdos1ActionPerformed(evt);
            }
        });
        getContentPane().add(Zapdos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 66, 40, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, 180));

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, -1, -1));

        party4.setText("jButton3");
        getContentPane().add(party4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 80, 70));

        party5.setText("jButton4");
        getContentPane().add(party5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 80, 70));

        party3.setText("jButton5");
        getContentPane().add(party3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 80, 70));

        party2.setText("jButton6");
        getContentPane().add(party2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 80, 70));

        party1.setText("jButton7");
        getContentPane().add(party1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 80, 70));

        party6.setText("jButton8");
        getContentPane().add(party6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 80, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, 180));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BulbasaurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulbasaurActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/1.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                 
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                 
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_BulbasaurActionPerformed

    private void SquirtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquirtleActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/7.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_SquirtleActionPerformed

    private void CharmanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharmanderActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/4.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_CharmanderActionPerformed

    private void PikachuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PikachuActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/25.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_PikachuActionPerformed

    private void ZapdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZapdosActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/145.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_ZapdosActionPerformed

    private void ArticunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticunoActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/144.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_ArticunoActionPerformed

    private void PichuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PichuActionPerformed
       ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/172.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_PichuActionPerformed

    private void MoltresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoltresActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/146.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_MoltresActionPerformed

    private void CyndaquilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CyndaquilActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/155.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_CyndaquilActionPerformed

    private void ChikoritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChikoritaActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/152.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_ChikoritaActionPerformed

    private void TotodileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotodileActionPerformed
       ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/158.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_TotodileActionPerformed

    private void ClefableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClefableActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/173.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_ClefableActionPerformed

    private void ElekidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElekidActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/239.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_ElekidActionPerformed

    private void IgglybuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgglybuffActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/174.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_IgglybuffActionPerformed

    private void TeddyursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeddyursaActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/216.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;  
    }//GEN-LAST:event_TeddyursaActionPerformed

    private void TogepiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TogepiActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/175.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_TogepiActionPerformed

    private void SmoochumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmoochumActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/238.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_SmoochumActionPerformed

    private void MagbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagbyActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/240.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_MagbyActionPerformed

    private void LugiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugiaActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/249.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_LugiaActionPerformed

    private void LatiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatiasActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/380.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_LatiasActionPerformed

    private void CelebiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelebiActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/251.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_CelebiActionPerformed

    private void TorchicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TorchicActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/255.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_TorchicActionPerformed

    private void TreekoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreekoActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/252.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_TreekoActionPerformed

    private void MudkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MudkipActionPerformed
         ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/258.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_MudkipActionPerformed

    private void LatiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatiosActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/381.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_LatiosActionPerformed

    private void TepigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TepigActionPerformed
       ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/498.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_TepigActionPerformed

    private void TurtwigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurtwigActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/387.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_TurtwigActionPerformed

    private void PiplupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiplupActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/393.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_PiplupActionPerformed

    private void RaikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaikuActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/243.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_RaikuActionPerformed

    private void ChimcharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChimcharActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/390.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_ChimcharActionPerformed

    private void SnivyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnivyActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/495.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_SnivyActionPerformed

    private void OshawottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OshawottActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/501.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_OshawottActionPerformed

    private void SuicuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuicuneActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/245.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_SuicuneActionPerformed

    private void EnteiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnteiActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/244.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_EnteiActionPerformed

    private void LarvitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LarvitarActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/246.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_LarvitarActionPerformed

    private void HoohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoohActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/250.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_HoohActionPerformed

    private void Zapdos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zapdos1ActionPerformed
        ImageIcon bbry = new ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_Front/145.png"));
        switch(counter)
        {
            case 1:
            {
                party1.setIcon(bbry);
                pokemons[(counter - 1)] = 145;
                break;
            }
            case 2:
            {
                party2.setIcon(bbry);
                pokemons[(counter - 1)] = 145;
                break;
            }case 3:
            {
                party3.setIcon(bbry);
                pokemons[(counter - 1)] = 145;
                break;
            }case 4:
            {
                party4.setIcon(bbry);
                pokemons[(counter - 1)] = 145;
                break;
            }case 5:
            {
                party5.setIcon(bbry);
                pokemons[(counter - 1)] = 145;
                break;
            }case 6:
            {
                party6.setIcon(bbry);
                pokemons[(counter - 1)] = 145;
                
                break;
            }
            default:
            {
                counter = 1;
                party1.setIcon(bbry);
                pokemons[(counter - 1)] = 145;
                break;
            }
        }
        counter++;
    }//GEN-LAST:event_Zapdos1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PokemonSwitch s = new PokemonSwitch(pokemons, livesPercentage);
        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Articuno;
    private javax.swing.JButton Bulbasaur;
    private javax.swing.JButton Celebi;
    private javax.swing.JButton Charmander;
    private javax.swing.JButton Chikorita;
    private javax.swing.JButton Chimchar;
    private javax.swing.JButton Clefable;
    private javax.swing.JButton Cyndaquil;
    private javax.swing.JButton Elekid;
    private javax.swing.JButton Entei;
    private javax.swing.JButton Hooh;
    private javax.swing.JButton Igglybuff;
    private javax.swing.JButton Larvitar;
    private javax.swing.JButton Latias;
    private javax.swing.JButton Latios;
    private javax.swing.JButton Lugia;
    private javax.swing.JButton Magby;
    private javax.swing.JButton Moltres;
    private javax.swing.JButton Mudkip;
    private javax.swing.JButton Oshawott;
    private javax.swing.JButton Pichu;
    private javax.swing.JButton Pikachu;
    private javax.swing.JButton Piplup;
    private javax.swing.JButton Raiku;
    private javax.swing.JButton Smoochum;
    private javax.swing.JButton Snivy;
    private javax.swing.JButton Squirtle;
    private javax.swing.JButton Suicune;
    private javax.swing.JButton Teddyursa;
    private javax.swing.JButton Tepig;
    private javax.swing.JButton Togepi;
    private javax.swing.JButton Torchic;
    private javax.swing.JButton Totodile;
    private javax.swing.JButton Treeko;
    private javax.swing.JButton Turtwig;
    private javax.swing.JButton Zapdos;
    private javax.swing.JButton Zapdos1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton party1;
    private javax.swing.JButton party2;
    private javax.swing.JButton party3;
    private javax.swing.JButton party4;
    private javax.swing.JButton party5;
    private javax.swing.JButton party6;
    // End of variables declaration//GEN-END:variables
}
