/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon;

/**
 *
 * @author PauloSenires
 */
public class PokemonSelection extends javax.swing.JFrame {

    /**
     * Creates new form PokemonSelection
     */
    public PokemonSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Bulbasaur = new javax.swing.JButton();
        Squirtle = new javax.swing.JButton();
        Charmander = new javax.swing.JButton();
        Pikachu = new javax.swing.JButton();
        Zapdos = new javax.swing.JButton();
        Articuno = new javax.swing.JButton();
        Pichu = new javax.swing.JButton();
        Moltres = new javax.swing.JButton();
        Cyndaquil = new javax.swing.JButton();
        Chikorita = new javax.swing.JButton();
        Totodile = new javax.swing.JButton();
        Clefable = new javax.swing.JButton();
        Elekid = new javax.swing.JButton();
        Igglybuff = new javax.swing.JButton();
        Teddyursa = new javax.swing.JButton();
        Togepi = new javax.swing.JButton();
        Smoochum = new javax.swing.JButton();
        Magby = new javax.swing.JButton();
        Lugia = new javax.swing.JButton();
        Latias = new javax.swing.JButton();
        Celebi = new javax.swing.JButton();
        Torchic = new javax.swing.JButton();
        Treeko = new javax.swing.JButton();
        Mudkip = new javax.swing.JButton();
        Latios = new javax.swing.JButton();
        Tepig = new javax.swing.JButton();
        Turtwig = new javax.swing.JButton();
        Piplup = new javax.swing.JButton();
        Raiku = new javax.swing.JButton();
        Chimchar = new javax.swing.JButton();
        Snivy = new javax.swing.JButton();
        Oshawott = new javax.swing.JButton();
        Suicune = new javax.swing.JButton();
        Entei = new javax.swing.JButton();
        Larvitar = new javax.swing.JButton();
        Hooh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Zapdos1 = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Bulbasaur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/bulbasaur.png"))); // NOI18N
        Bulbasaur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulbasaurActionPerformed(evt);
            }
        });
        getContentPane().add(Bulbasaur);
        Bulbasaur.setBounds(20, 66, 40, 40);

        Squirtle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/squirtle.png"))); // NOI18N
        Squirtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquirtleActionPerformed(evt);
            }
        });
        getContentPane().add(Squirtle);
        Squirtle.setBounds(136, 66, 40, 40);

        Charmander.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/charmander.png"))); // NOI18N
        Charmander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharmanderActionPerformed(evt);
            }
        });
        getContentPane().add(Charmander);
        Charmander.setBounds(78, 66, 40, 40);

        Pikachu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/pikachu.png"))); // NOI18N
        Pikachu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PikachuActionPerformed(evt);
            }
        });
        getContentPane().add(Pikachu);
        Pikachu.setBounds(194, 66, 40, 40);

        Zapdos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/zapdos.png"))); // NOI18N
        Zapdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZapdosActionPerformed(evt);
            }
        });
        getContentPane().add(Zapdos);
        Zapdos.setBounds(310, 66, 40, 40);

        Articuno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/articuno.png"))); // NOI18N
        Articuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticunoActionPerformed(evt);
            }
        });
        getContentPane().add(Articuno);
        Articuno.setBounds(252, 66, 40, 40);

        Pichu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/pichu.png"))); // NOI18N
        Pichu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PichuActionPerformed(evt);
            }
        });
        getContentPane().add(Pichu);
        Pichu.setBounds(252, 112, 40, 40);

        Moltres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/moltres.png"))); // NOI18N
        Moltres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoltresActionPerformed(evt);
            }
        });
        getContentPane().add(Moltres);
        Moltres.setBounds(20, 112, 40, 40);

        Cyndaquil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/cyndaquil.png"))); // NOI18N
        Cyndaquil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CyndaquilActionPerformed(evt);
            }
        });
        getContentPane().add(Cyndaquil);
        Cyndaquil.setBounds(136, 112, 40, 40);

        Chikorita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/chikorita.png"))); // NOI18N
        Chikorita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChikoritaActionPerformed(evt);
            }
        });
        getContentPane().add(Chikorita);
        Chikorita.setBounds(78, 112, 40, 40);

        Totodile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/totodile.png"))); // NOI18N
        Totodile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotodileActionPerformed(evt);
            }
        });
        getContentPane().add(Totodile);
        Totodile.setBounds(194, 112, 40, 40);

        Clefable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/cleffa.png"))); // NOI18N
        Clefable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClefableActionPerformed(evt);
            }
        });
        getContentPane().add(Clefable);
        Clefable.setBounds(310, 112, 40, 40);

        Elekid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/elekid.png"))); // NOI18N
        Elekid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElekidActionPerformed(evt);
            }
        });
        getContentPane().add(Elekid);
        Elekid.setBounds(252, 158, 40, 40);

        Igglybuff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/igglybuff.png"))); // NOI18N
        Igglybuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgglybuffActionPerformed(evt);
            }
        });
        getContentPane().add(Igglybuff);
        Igglybuff.setBounds(20, 158, 40, 40);

        Teddyursa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/teddiursa.png"))); // NOI18N
        Teddyursa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeddyursaActionPerformed(evt);
            }
        });
        getContentPane().add(Teddyursa);
        Teddyursa.setBounds(136, 158, 40, 40);

        Togepi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/togepi.png"))); // NOI18N
        Togepi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TogepiActionPerformed(evt);
            }
        });
        getContentPane().add(Togepi);
        Togepi.setBounds(78, 158, 40, 40);

        Smoochum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/smoochum.png"))); // NOI18N
        Smoochum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmoochumActionPerformed(evt);
            }
        });
        getContentPane().add(Smoochum);
        Smoochum.setBounds(194, 158, 40, 40);

        Magby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/magby.png"))); // NOI18N
        Magby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagbyActionPerformed(evt);
            }
        });
        getContentPane().add(Magby);
        Magby.setBounds(310, 158, 40, 40);

        Lugia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/lugia.png"))); // NOI18N
        Lugia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugiaActionPerformed(evt);
            }
        });
        getContentPane().add(Lugia);
        Lugia.setBounds(252, 204, 40, 40);

        Latias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/latias.png"))); // NOI18N
        Latias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatiasActionPerformed(evt);
            }
        });
        getContentPane().add(Latias);
        Latias.setBounds(252, 250, 40, 40);

        Celebi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/celebi.png"))); // NOI18N
        Celebi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelebiActionPerformed(evt);
            }
        });
        getContentPane().add(Celebi);
        Celebi.setBounds(20, 250, 40, 40);

        Torchic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/torchic.png"))); // NOI18N
        Torchic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TorchicActionPerformed(evt);
            }
        });
        getContentPane().add(Torchic);
        Torchic.setBounds(136, 250, 40, 40);

        Treeko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/treecko.png"))); // NOI18N
        Treeko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreekoActionPerformed(evt);
            }
        });
        getContentPane().add(Treeko);
        Treeko.setBounds(78, 250, 40, 40);

        Mudkip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/mudkip.png"))); // NOI18N
        Mudkip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MudkipActionPerformed(evt);
            }
        });
        getContentPane().add(Mudkip);
        Mudkip.setBounds(194, 250, 40, 40);

        Latios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/latios.png"))); // NOI18N
        Latios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatiosActionPerformed(evt);
            }
        });
        getContentPane().add(Latios);
        Latios.setBounds(310, 250, 40, 40);

        Tepig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/tepig.png"))); // NOI18N
        Tepig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TepigActionPerformed(evt);
            }
        });
        getContentPane().add(Tepig);
        Tepig.setBounds(252, 296, 40, 40);

        Turtwig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/turtwig.png"))); // NOI18N
        Turtwig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurtwigActionPerformed(evt);
            }
        });
        getContentPane().add(Turtwig);
        Turtwig.setBounds(20, 296, 40, 40);

        Piplup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/piplup.png"))); // NOI18N
        Piplup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiplupActionPerformed(evt);
            }
        });
        getContentPane().add(Piplup);
        Piplup.setBounds(136, 296, 40, 40);

        Raiku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/raikou.png"))); // NOI18N
        Raiku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaikuActionPerformed(evt);
            }
        });
        getContentPane().add(Raiku);
        Raiku.setBounds(20, 204, 40, 40);

        Chimchar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/chimchar.png"))); // NOI18N
        Chimchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChimcharActionPerformed(evt);
            }
        });
        getContentPane().add(Chimchar);
        Chimchar.setBounds(78, 296, 40, 40);

        Snivy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/snivy.png"))); // NOI18N
        Snivy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnivyActionPerformed(evt);
            }
        });
        getContentPane().add(Snivy);
        Snivy.setBounds(194, 296, 40, 40);

        Oshawott.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/oshawott.png"))); // NOI18N
        Oshawott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OshawottActionPerformed(evt);
            }
        });
        getContentPane().add(Oshawott);
        Oshawott.setBounds(310, 296, 40, 40);

        Suicune.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/suicune.png"))); // NOI18N
        Suicune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuicuneActionPerformed(evt);
            }
        });
        getContentPane().add(Suicune);
        Suicune.setBounds(136, 204, 40, 40);

        Entei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/entei.png"))); // NOI18N
        Entei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnteiActionPerformed(evt);
            }
        });
        getContentPane().add(Entei);
        Entei.setBounds(78, 204, 40, 40);

        Larvitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/larvitar.png"))); // NOI18N
        Larvitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LarvitarActionPerformed(evt);
            }
        });
        getContentPane().add(Larvitar);
        Larvitar.setBounds(194, 204, 40, 40);

        Hooh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/ho-oh.png"))); // NOI18N
        Hooh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoohActionPerformed(evt);
            }
        });
        getContentPane().add(Hooh);
        Hooh.setBounds(310, 204, 40, 40);

        jLabel1.setFont(new java.awt.Font("Lao UI", 0, 14)); // NOI18N
        jLabel1.setText("Select your team!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 11, 139, 49);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 190, 256, 180);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 180, 256, 180);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 190, 256, 180);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 256, 180);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 0, 256, 180);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/images.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 180, 256, 180);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 70, 73, 23);

        Zapdos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pokemon-Java/Pokemon_PC/zapdos.png"))); // NOI18N
        Zapdos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Zapdos1ActionPerformed(evt);
            }
        });
        getContentPane().add(Zapdos1);
        Zapdos1.setBounds(310, 66, 40, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BulbasaurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulbasaurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulbasaurActionPerformed

    private void SquirtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquirtleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SquirtleActionPerformed

    private void CharmanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharmanderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharmanderActionPerformed

    private void PikachuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PikachuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PikachuActionPerformed

    private void ZapdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZapdosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZapdosActionPerformed

    private void ArticunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArticunoActionPerformed

    private void PichuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PichuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PichuActionPerformed

    private void MoltresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoltresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoltresActionPerformed

    private void CyndaquilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CyndaquilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CyndaquilActionPerformed

    private void ChikoritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChikoritaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChikoritaActionPerformed

    private void TotodileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotodileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotodileActionPerformed

    private void ClefableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClefableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClefableActionPerformed

    private void ElekidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElekidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElekidActionPerformed

    private void IgglybuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgglybuffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IgglybuffActionPerformed

    private void TeddyursaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeddyursaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeddyursaActionPerformed

    private void TogepiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TogepiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TogepiActionPerformed

    private void SmoochumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmoochumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SmoochumActionPerformed

    private void MagbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MagbyActionPerformed

    private void LugiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugiaActionPerformed

    private void LatiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatiasActionPerformed

    private void CelebiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelebiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelebiActionPerformed

    private void TorchicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TorchicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TorchicActionPerformed

    private void TreekoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreekoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TreekoActionPerformed

    private void MudkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MudkipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MudkipActionPerformed

    private void LatiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatiosActionPerformed

    private void TepigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TepigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TepigActionPerformed

    private void TurtwigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurtwigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TurtwigActionPerformed

    private void PiplupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiplupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PiplupActionPerformed

    private void RaikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaikuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RaikuActionPerformed

    private void ChimcharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChimcharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChimcharActionPerformed

    private void SnivyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnivyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnivyActionPerformed

    private void OshawottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OshawottActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OshawottActionPerformed

    private void SuicuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuicuneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuicuneActionPerformed

    private void EnteiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnteiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnteiActionPerformed

    private void LarvitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LarvitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LarvitarActionPerformed

    private void HoohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoohActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoohActionPerformed

    private void Zapdos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Zapdos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Zapdos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Articuno;
    private javax.swing.JButton Bulbasaur;
    private javax.swing.JButton Celebi;
    private javax.swing.JButton Charmander;
    private javax.swing.JButton Chikorita;
    private javax.swing.JButton Chimchar;
    private javax.swing.JButton Clefable;
    private javax.swing.JButton Cyndaquil;
    private javax.swing.JButton Elekid;
    private javax.swing.JButton Entei;
    private javax.swing.JButton Hooh;
    private javax.swing.JButton Igglybuff;
    private javax.swing.JButton Larvitar;
    private javax.swing.JButton Latias;
    private javax.swing.JButton Latios;
    private javax.swing.JButton Lugia;
    private javax.swing.JButton Magby;
    private javax.swing.JButton Moltres;
    private javax.swing.JButton Mudkip;
    private javax.swing.JButton Oshawott;
    private javax.swing.JButton Pichu;
    private javax.swing.JButton Pikachu;
    private javax.swing.JButton Piplup;
    private javax.swing.JButton Raiku;
    private javax.swing.JButton Smoochum;
    private javax.swing.JButton Snivy;
    private javax.swing.JButton Squirtle;
    private javax.swing.JButton Suicune;
    private javax.swing.JButton Teddyursa;
    private javax.swing.JButton Tepig;
    private javax.swing.JButton Togepi;
    private javax.swing.JButton Torchic;
    private javax.swing.JButton Totodile;
    private javax.swing.JButton Treeko;
    private javax.swing.JButton Turtwig;
    private javax.swing.JButton Zapdos;
    private javax.swing.JButton Zapdos1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
